version: 2


build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
    
  jobs:
      post_create_environment:
        - pip install poetry
        # - poetry config virtualenvs.create false
      post_install:
        - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with doc

mkdocs:
  configuration: mkdocs.yml