coverage:
  status:
    patch:
      default:
        target: 80%
    project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      default:
        # basic
        target: 80% #default
        threshold: 0%
        base: auto 