name: CI for Production Branch
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Poetry
        run: pip install poetry

      - name: Install asltk project dependecies
        run: poetry install

      - name: Install zbar for pyzbar
        run: sudo apt-get update && sudo apt-get install -y libzbar0

      - name: Run code formatting check
        run: poetry run task lint-check

      - name: Run project tests
        run: poetry run task test --cov-report=xml

      - name: Show-up test coverage (codecov)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.0


      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Poetry
        run: pip install poetry

      - name: Install asltk project dependecies
        run: poetry install

      - name: Run code formatting check
        run: poetry run task lint-check

      - name: Run project tests
        run: poetry run task test --cov-report=xml

      - name: Show-up test coverage (codecov)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.0


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  

      - name: Install Poetry
        run: pip install poetry

      - name: Install asltk project dependecies
        run: poetry install

      - name: Install zbar for pyzbar
        run: brew install zbar

      - name: Run code formatting check
        run: poetry run task lint-check

      - name: Run project tests
        run: poetry run task test --cov-report=xml

      - name: Show-up test coverage (codecov)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
